
---
---
<div class="title-box">
  <h1>Oracle Homework Assignment </h1>
</div>

<div class="textbox">
  <p>Hello, I'm Ada(Yumeng) Qi, a first-year biostatistics student at Columbia University. I'm very grateful for the opportunity to interview with Oracle. I've developed a website using R Markdown, leveraging its interactive functionalities to enhance user engagement and accessibility. Thank you for considering my application.</p>
</div>


<div class="textbox">
  <p>In this exploratory <a href="report.html">study</a>, we aim to investigate the frequency of hospitalizations over the past six months and explore potential associations with demographic factors, diabetes-related indicators, quality of life measures, and other health-related variables.</p>

  <p>Main Research Questions:</p>
  <ul>
    <li>Does diagnosed patients have larger frequency of hospitalizations over six months?(PSM,NB regression, ZINB)</li>
    <li>Are patients with Type 1 Diabetes more likely to adhere to medication regimens, as indicated by lower scores on the Medication Adherence Scale (MMAS)? Furthermore, among Type 1 Diabetes patients, does increased non-adherence, reflected by higher MMAS scores, correlate with a higher frequency of hospitalizations? (contingency table chi-square test, ZINB) </li>
    <li>For Type2 Diabetes patients, how to predict the possibility of hospitalizations in 6 months? (LASSO)</li>
  </ul>
</div>

```{css, echo=FALSE}

.title-box {
  background-color: rgba(255, 255, 255, 0.8);
  padding: 10px;
  border-radius: 5px;
  text-align: center;
  margin: 20px;
}

.textbox {
  background-color: rgba(255, 255, 255, 0.8);
  padding: 10px;
  border-radius: 5px;
  margin: 10px 0;
  line-height: 2; /* Adjust the line height as needed */
}

.textbox iframe {
  display: block;
  margin: 0 auto;
}